{% set name = "pyGLFW" %}
{% set pypi_name = "glfw" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: d3e8f9069dea62838b1eaf91ff40b684871eff099460de23ad7d861ad3f21adc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # glfw is not / cannot be packaged for Python 2.7 on conda-forge for now, so
  # skip the build of pyGLFW on this platform.
  skip: True  # [win and py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - glfw

test:
  imports:
    - glfw

about:
  home: https://github.com/FlorianRhiem/pyGLFW
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'This module provides Python bindings for GLFW'

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
