{% set name = "pyGLFW" %}
{% set pypi_name = "glfw" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 077111a150ff09bc302c5e4ae265a5eb6aeaff0c8b01f727f7fb34e3764bb8e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - glfw

test:
  requires:
    - python {{ python_min }}
  imports:
    - glfw

about:
  home: https://github.com/FlorianRhiem/pyGLFW
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This module provides Python bindings for GLFW

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
