{% set name = "pyGLFW" %}
{% set pypi_name = "glfw" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e6aa27e6d979c3fc0637812912e558150d3722c0be2cf9f29e8e0615b6c29ad6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # glfw is not / cannot be packaged for Python 2.7 on conda-forge for now, so
  # skip the build of pyGLFW on this platform.
  skip: true  # [win and py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - glfw

test:
  imports:
    - glfw

about:
  home: https://github.com/FlorianRhiem/pyGLFW
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This module provides Python bindings for GLFW

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
