{% set name = "pyGLFW" %}
{% set pypi_name = "glfw" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 90e90d328b0b26fed6e1631d21801e2d8a7a0c5dcb480e733c177567ec9666f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - glfw

test:
  imports:
    - glfw

about:
  home: https://github.com/FlorianRhiem/pyGLFW
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This module provides Python bindings for GLFW

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
