travis:
  secure:
    BINSTAR_TOKEN: qSAQ7oKcxIVlMNgOF7AFqj1Fd2KANizFy4/z1Z5WHrI6+rAsbTB9OMQeCzIgUYBHtE/Rt+Z7gPOgh1Y3nuuS/uHnFymv0Nsoveu1zxzs5MYh1e8ep0xn+h3Nuc7hUU/8LObxwE5/gOWRvUvy+o6X/Dd7NZNYAJhDMt3Hy4ZpKyeAdcvZ+w1rFzCoKhP8Wy31v1R973W714IB1EO4e8bOPb4hpt/SuatXtnFRrl0fhtEtHhezywphGBH0g36vDFv2d78RHkctFGt/xIPOWwpMV3LkPqdTD5d6FcDkQfVFlj1MXBW48HK27kBi8sQw6oOW4IH8aRDLoxB9TCputlAbUuUIhqom4LDZup6k8hMReTKE5r8jud9gtdcCiuaw5zcFLaDCnwJEuAvzgjqCruiy/7WUBMJM/FOwwguODwoPMdoJJ56OvMKFBgyQPeTPvhVVUoOSD1Qhvw38Pq2Sg2FlQidS/ORC9VEnuZTERmp0ynGKntImIx46NI56TuxO0B973vWvhVwT9Hhu/J4ZzVXjVPY9IB/6TJUsb7RkSKCPh20XQTvLZ49rDswFwveheZKaQ3Z3B+H3REOZ24iWsCwFfhYkgTOIiiAhmPSkYddyg6Q1cPcMLwPxfbFmzltx3kvdpci23yBOIL5ljENMZdPFgU2fpfqgGujbhBdmMTGcFTc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
